-- Add missing columns to dogs table that the add-dog form uses

ALTER TABLE dogs ADD COLUMN IF NOT EXISTS color TEXT;
ALTER TABLE dogs ADD COLUMN IF NOT EXISTS microchipped BOOLEAN DEFAULT FALSE;
ALTER TABLE dogs ADD COLUMN IF NOT EXISTS vaccination_expiry DATE;
ALTER TABLE dogs ADD COLUMN IF NOT EXISTS flea_treatment BOOLEAN DEFAULT FALSE;
ALTER TABLE dogs ADD COLUMN IF NOT EXISTS worming_treatment BOOLEAN DEFAULT FALSE;
ALTER TABLE dogs ADD COLUMN IF NOT EXISTS heartworm_prevention BOOLEAN DEFAULT FALSE;
ALTER TABLE dogs ADD COLUMN IF NOT EXISTS current_medications JSONB;
ALTER TABLE dogs ADD COLUMN IF NOT EXISTS medication_requirements TEXT;
ALTER TABLE dogs ADD COLUMN IF NOT EXISTS can_be_given_treats BOOLEAN DEFAULT TRUE;
ALTER TABLE dogs ADD COLUMN IF NOT EXISTS resource_guarding BOOLEAN DEFAULT FALSE;
ALTER TABLE dogs ADD COLUMN IF NOT EXISTS excessive_barking BOOLEAN DEFAULT FALSE;
ALTER TABLE dogs ADD COLUMN IF NOT EXISTS leash_pulling BOOLEAN DEFAULT FALSE;
ALTER TABLE dogs ADD COLUMN IF NOT EXISTS house_trained BOOLEAN DEFAULT TRUE;
ALTER TABLE dogs ADD COLUMN IF NOT EXISTS crate_trained BOOLEAN DEFAULT FALSE;
ALTER TABLE dogs ADD COLUMN IF NOT EXISTS aggression_triggers TEXT;
ALTER TABLE dogs ADD COLUMN IF NOT EXISTS behavioral_challenges TEXT;
ALTER TABLE dogs ADD COLUMN IF NOT EXISTS training_needs TEXT;
ALTER TABLE dogs ADD COLUMN IF NOT EXISTS good_with_cats BOOLEAN DEFAULT FALSE;
ALTER TABLE dogs ADD COLUMN IF NOT EXISTS good_with_children BOOLEAN DEFAULT TRUE;
ALTER TABLE dogs ADD COLUMN IF NOT EXISTS good_with_strangers BOOLEAN DEFAULT TRUE;
ALTER TABLE dogs ADD COLUMN IF NOT EXISTS play_style TEXT;
ALTER TABLE dogs ADD COLUMN IF NOT EXISTS escape_artist BOOLEAN DEFAULT FALSE;
ALTER TABLE dogs ADD COLUMN IF NOT EXISTS fence_jumper BOOLEAN DEFAULT FALSE;
ALTER TABLE dogs ADD COLUMN IF NOT EXISTS recall_reliability TEXT DEFAULT 'good';
ALTER TABLE dogs ADD COLUMN IF NOT EXISTS vet_address TEXT;
ALTER TABLE dogs ADD COLUMN IF NOT EXISTS emergency_medical_consent BOOLEAN DEFAULT FALSE;
ALTER TABLE dogs ADD COLUMN IF NOT EXISTS max_vet_cost_approval DECIMAL(10,2);
ALTER TABLE dogs ADD COLUMN IF NOT EXISTS feeding_schedule TEXT;
ALTER TABLE dogs ADD COLUMN IF NOT EXISTS special_requirements TEXT;
ALTER TABLE dogs ADD COLUMN IF NOT EXISTS favorite_activities TEXT;

-- Also add has_dogs column to profiles
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS has_dogs BOOLEAN DEFAULT FALSE;
